### ISSUE TITLE
Course of Study: "Unique courses" section & link to school-scoped third-party database interface

### ISSUE THREAD

**Issue by TroyRobinson** [tulsaschoolsdata/courses#2]
**Mockup**: https://www.figma.com/file/ZUTuZLnC305DO8dURRWt6j/Find-a-School-Course-of-Study?node-id=2%3A2
**Project Plan**: https://app.smartsheet.com/sheets/Q9j7rR4j62Vfgj9MpQ39C2rgw8qmwfF86Mw5JHC1

<img width="735" alt="image" src="https://user-images.githubusercontent.com/24643126/174405250-1a360b07-4b95-4887-9c36-3167d5b7b1b5.png">
- screenshot is up-to-date as of 06/17/2022

### Requirements

- [ ] Shows a list of courses that are not in 75% of other schools in the same tier, i.e. high school, middle school, elementary school.
- [ ] A link, scoped to the school, takes you to a third-party database interface. See: https://github.com/tulsaschoolsdata/courses/issues/1
- [ ] Course titles in section list are pulled from the third-party database via its API
